SELECT [STUDENT_NUMBER], [COURSE_NAME], [Credit_Type], avg([PERCENT]) as [AVG_PERCENT]
FROM {{ ref('q3_grades_with_course_id')}}
WHERE FINALGRADENAME = 'Q1' OR FINALGRADENAME = 'Q2' OR FINALGRADENAME = 'Q3'
GROUP BY [STUDENT_NUMBER], [COURSE_NAME], [Credit_Type]