version: 2

sources:
  - name: kickboard_data
    database: northstar
    schema: dbo
    tables:
      - name: 1516_KB Data
      - name: 1617_KB Data
      - name: 1718_KB Data
      - name: 1819_KB Data