SELECT [STUDENT_NUMBER], [SECTIONID], [COURSE_NAME], avg([PERCENT]) AS grade
FROM {{ source('c2020_grades_by_quarter','c2020_apr24_grade_by_quarter')}}
WHERE [FINALGRADENAME] = 'Q1' OR [FINALGRADENAME] = 'Q2' OR [FINALGRADENAME] = 'Q3'
GROUP BY [STUDENT_NUMBER], [SECTIONID], [COURSE_NAME]
